### ISSUE TITLE
Migrate this to hetio org?

### ISSUE THREAD

**Issue by vincerubinetti** [hetio/xswap#12]

**Comment by dhimmel** [comment]
It does probably make sense to have this under the same organization as the `hetio` codebase (or `hetnetpy` pending https://github.com/hetio/hetio/issues/40). However, we'll probably want to keep the `xswap-manuscript` and other application repos under greenelab.

Along with the relocation, we should make sure to update the README with the relevant acknowledgements to the Greene Lab, the NCSU folks if any of @kkloste's work is included, and funding sources.

**Comment by dhimmel** [comment]
Nice repo is now https://github.com/hetio/xswap!
